spring:
  application:
    name: discovery-service

# configuration for not to register with server(itself)
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
server:
  port: 8761