spring:
  application:
    name: course-service
  datasource:
    url: jdbc:postgresql://localhost:5432/coursedb
    username: user
    password: user123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
info:
  app:
    name: "course-service"
    description:  "This is course service"
    version: "1.0"