server:
  port: 9093
spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  application:
    name: video-service

  data:
    mongodb:
      host: localhost
      port: 27017
      database: videodb
  config:
    import: "configserver:http://localhost:9094/"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
info:
  app:
    name: "video-service"
    description:  "This is video service"
    version: "1.0"



resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 1000

