server:
  port: 9093
spring:
  application:
    name: video-service

  data:
    mongodb:
      host: localhost
      port: 27017
      database: videodb
  config:
    import: "configserver:http://localhost:9094/"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
info:
  app:
    name: "video-service"
    description:  "This is video service"
    version: "1.0"

